name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: "test App"
    runs-on: ubuntu-latest
    steps:
      - name: Show Text
        run: |
            echo "ini build app"
  build:
    name: "build App"
    runs-on: ubuntu-latest
    steps:
      - name: Show Text
        run: |
            echo "ini build app"
            
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
          echo "ini deploy aplikasi"

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "34.128.122.90"
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: "22"
        script: whoami
