name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "build App"
    runs-on: ubuntu-latest
    steps:
      - name: Show Text
        run: /
            echo "ini build app"
            
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: "ini deploy aplikasi"

    - name: Set up SSH
      uses: appleboy/ssh-agent@v1.0.0
      with:
        host:  ${{ secrets.DEPLOY_HOST }} 35.202.70.17
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: whoami
